- name: Install nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs-setup
- name: Setup Application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup
 